name: documentation

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths:
      - docs/**
      - fluent.*/docs/**
      - fluent.syntax/src/main/kotlin/org/projectfluent/syntax/ast/Nodes.kt
      - fluent.*/build.gradle.kts
      - .github/workflows/documentation.yml
  pull_request:
    branches:
      - master
    paths:
      - docs/**
      - fluent.*/docs/**
      - fluent.syntax/src/main/kotlin/org/projectfluent/syntax/ast/Nodes.kt
      - fluent.*/build.gradle.kts
      - .github/workflows/documentation.yml

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install Sphinx fluent.pygments
      - name: sphinx-build
        run: |
          ./scripts/build-docs --to-publish fluent-kotlin
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: _build/fluent-kotlin
